name: 'Install ghelper'
description: 'Install ghelper to use in your workflow.'

runs:
  using: 'composite'
  steps:
    - name: Checkout ghelper repository
      uses: actions/checkout@v4
      with:
        repository: '3lvia/ghelper'
        path: '/tmp/ghelper'

    - name: Install ghelper
      shell: bash
      run: |
        cp /tmp/ghelper/ghelper /usr/local/bin/ghelper
        chmod +x /usr/local/bin/ghelper
        rm -rf /tmp/ghelper
