#!/bin/bash


# Set up

set -e
SCRIPT_PATH="$(cd -- "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P)"
source "$SCRIPT_PATH/scripts/common"


# Subcommands

case $1 in
  commit)
    "$SCRIPT_PATH/scripts/commit" "${@:2}"
    ;;
  exec)
    "$SCRIPT_PATH/scripts/exec" "${@:2}"
    ;;
  *)
    root_help
    ;;
esac
