#!/bin/bash

set -e


# Check if required software is installed

if ! command -v git &> /dev/null; then
  echo "git could not be found."
  exit 1
fi

if ! command -v gh &> /dev/null; then
  echo "GitHub CLI (gh) could not be found."
  exit 1
fi

if ! command -v tput &> /dev/null; then
  echo "tput could not be found."
  exit 1
fi


# Set colors

RED="$(tput setaf 1)"
GREEN="$(tput setaf 2)"
BLUE="$(tput setaf 4)"
NORMAL="$(tput sgr0)"
UNDERLINE="$(tput smul)"


# Help

root_help() {
  echo ""
  echo "Usage: ghelper [subcommand] [options]"
  echo ""
  echo "Subcommand:"
  echo ""
  echo "commit: Create a new branch, add/delete files, and open/merge a pull request."
  echo "exec:   Execute a shell command in multiple git repositories."
  echo ""
  echo "-h, --help: Show this help message."
  exit 0
}
